apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: groundcover
  namespace: argocd
spec:
  project: default
  source:
    chart: groundcover
    repoURL: https://helm.groundcover.com
    targetRevision: 1.8.61
    helm:
      releaseName: groundcover
  destination:
    server: "https://kubernetes.default.svc"
    namespace: groundcover
