# updatecli.d/default.yaml
name: Argocd Autodiscovery Example

autodiscovery:
  # 1 PR per a chart
  groupby: individual
  # Only update on major versions
  versionfilter:
      kind: semver
      pattern: minor
  # scmid is applied to all crawlers
  scmid: default
  # actionid is applied to all crawlers
  actionid: default
  crawlers:
    argocd:
      # To ignore specific path
      # ignore:
      #   # Ignore manifest match path "dev/*.yaml"
      #   - path: dev/*.yaml
      #   # Ignore any Helm chart named "kubewarden-crds"
      #   - charts:
      #       "kubewarden-crds": ""
      #   # Ignore any helm chart repository named "https://charts.jetstack.io"
        # - repositories:
        #     - "https://bitnami-labs.github.io/sealed-secrets"

      #   # Ignore any Helm chart named "kubewarden-crds" in manifest path "dev/*.yaml"
      #   - path: dev/*.yaml
      #     charts:
      #       "kubewarden-crds": ""
      # Only accepts the same rule than ignore
      #only:
      #  - path: helmfile.d/*
      #  - charts:
      #      "kubewarden-crds": ""
      #  - repositories:
      #      - "https://charts.jetstack.io"
      #

scms:
  default:
    kind: github
    spec:
      user: "cloudoutloud"
      username: "cloudoutloud"
      owner: "cloudoutloud"
      repository: "test-updatecli"
      token: "${{ secrets.PAT_TOKEN }}"
      branch: "add-actions-updates"

actions:
  default:
    kind: "github/pullrequest"
    spec:
      mergemethod: "squash"
    scmid: "default"